#!/bin/sh

set -e -x

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path="etcd-certs"
mkdir -p ${depot_path}

generate_ca() {
  common_name=$1
  depot_path=$2
  output_path=$3
  # CA to distribute to etcd clients and servers
  certstrap --depot-path ${depot_path} init --passphrase '' --common-name $common_name
  mv -f ${depot_path}/$common_name.crt ${depot_path}/$output_path.crt
  mv -f ${depot_path}/$common_name.key ${depot_path}/$output_path.key
}

generate_ca "etcdCA" etcd-certs "etcd-ca"

generate_cluster_certs() {
  common_name=$1
  domain=$2
  ca_name=$3
  depot_path=$4
  output_name=$5

  if [ ${domain} != "" ]; then
    domain_argument="--domain ${domain}"
  fi

  # Server certificate to share across the etcd cluster
  certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name $common_name $domain_argument
  certstrap --depot-path ${depot_path} sign $common_name --CA $ca_name
  mv -f ${depot_path}/${common_name}.key ${depot_path}/${output_name}.key
  mv -f ${depot_path}/${common_name}.csr ${depot_path}/${output_name}.csr
  mv -f ${depot_path}/${common_name}.crt ${depot_path}/${output_name}.crt
}

generate_cluster_certs "cf-etcd.service.cf.internal" '*.cf-etcd.service.cf.internal,cf-etcd.service.cf.internal' etcd-ca etcd-certs server
generate_cluster_certs "clientName" "" etcd-ca etcd-certs client

# Client certificate to distribute to jobs that access etcd
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name 'clientName'
certstrap --depot-path ${depot_path} sign clientName --CA etcd-ca
mv -f ${depot_path}/clientName.key ${depot_path}/client.key
mv -f ${depot_path}/clientName.csr ${depot_path}/client.csr
mv -f ${depot_path}/clientName.crt ${depot_path}/client.crt

# CA to distribute across etcd peers
certstrap --depot-path ${depot_path} init --passphrase '' --common-name peerCA
mv -f ${depot_path}/peerCA.crt ${depot_path}/peer-ca.crt
mv -f ${depot_path}/peerCA.key ${depot_path}/peer-ca.key

# Client certificate to distribute across etcd peers
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name cf-etcd.service.cf.internal --domain '*.cf-etcd.service.cf.internal,cf-etcd.service.cf.internal'
certstrap --depot-path ${depot_path} sign cf-etcd.service.cf.internal --CA peer-ca
mv -f ${depot_path}/cf-etcd.service.cf.internal.key ${depot_path}/peer.key
mv -f ${depot_path}/cf-etcd.service.cf.internal.csr ${depot_path}/peer.csr
mv -f ${depot_path}/cf-etcd.service.cf.internal.crt ${depot_path}/peer.crt
